services:
  api:
    restart: always
    build:
      context: ./api
    ports:
      - "9900:8080"
    # depends_on: # <--- COMMENT THIS ENTIRE LINE OUT
    #   - postgres # <--- COMMENT THIS ENTIRE LINE OUT
    environment:
      - DATABASE_TYPE=postgres # postgres|sqlite
      # Corrected DATABASE_URL: removed space after 'postgres:', URL-encoded '#' to '%23'
      - DATABASE_URL=postgresql://postgres.rfwlmfslfgncohlcbzjc:1dT48jferVerrt4nKlPpf3e@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
      # - DATABASE_URL=/root/sqlite3/formulosity.db # <--- This was already commented, good.
      - SURVEYS_DIR=/root/surveys
      - UPLOADS_DIR=/root/uploads
      - WEBHOOKS_ENABLED=FALSE
    volumes:
      - ./api/surveys:/root/surveys
      # - ./api/sqlite3:/root/sqlite3 # <--- COMMENT THIS LINE OUT (optional, but good cleanup)
      - ./api/uploads:/root/uploads
  ui:
    restart: always
    build:
      context: ./ui
    ports:
      - "3000:3000"
    environment:
      - CONSOLE_API_ADDR_INTERNAL=http://api:8080
      - CONSOLE_API_ADDR=http://localhost:9900
      - IRON_SESSION_SECRET=e75af92dffba8065f2730472f45f2046941fe35f361739d31992f42d88d6bf6c
      - HTTP_BASIC_AUTH=user:pass
    depends_on:
      - api
# postgres: # <--- COMMENT THIS ENTIRE BLOCK OUT
#   image: postgres:16.0-alpine
#   restart: always
#   environment:
#     - POSTGRES_USER=user
#     - POSTGRES_PASSWORD=pass
#     - POSTGRES_DB=formulosity
#   ports:
#     - "5432:5432"
#   volumes:
#     - ./api/postgres-data:/var/lib/postgresql/data