services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=formulosity
    ports:
      - "5432:5432"
    volumes:
      - ./api/postgres-data:/var/lib/postgresql/data
    logging:
      driver: none

  api:
    restart: always
    build:
      context: ./api
    ports:
      - "9900:8080"
    depends_on:
      - postgres
    environment:
      - LOG_LEVEL=debug
      - DATABASE_TYPE=postgres
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/formulosity?sslmode=disable
      - SURVEYS_DIR=/root/surveys
    volumes:
      - ./api/surveys:/root/surveys

  ui:
    restart: always
    build:
      context: ./ui
      args:
        - NEXT_PUBLIC_CONSOLE_API_ADDR=http://localhost:9900
    ports:
      - "3000:3000"
    environment:
      - CONSOLE_API_ADDR=http://api:8080
      - IRON_SESSION_SECRET=e75af92dffba8065f2730472f45f2046941fe35f361739d31992f42d88d6bf6c
      - HTTP_BASIC_AUTH=user:pass
    depends_on:
      - postgres
      - api

volumes:
  dbvolume:
    driver: local
