version: "3.5"

services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=formulosity
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: none

  api:
    restart: always
    build:
      context: .
    ports:
      - "9900:8080"
    depends_on:
      - postgres
    environment:
      - LOG_LEVEL=debug
      - UI_ADDR=http://localhost:3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/formulosity?sslmode=disable
      - SURVEYS_DIR=/root/surveys
    volumes:
      - ./surveys:/root/surveys

  ui:
    restart: always
    build:
      context: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - api

volumes:
  dbvolume:
    driver: local
