name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check out code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./api

  test:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Tests
        working-directory: ./api
        run: go test -v -bench=. -race ./...

  lint-ui:
    name: Lint UI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node_version: ${{ matrix.node_version }}

      - name: run CI
        working-directory: ./ui
        run: |
          npm install
          npm run lint
